# Generated by Django 2.2.10 on 2020-03-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ign',
            field=models.CharField(default='None', max_length=16),
        ),
    ]
