# Generated by Django 2.2.10 on 2020-04-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_ign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ign',
        ),
    ]
