# Generated by Django 2.1.12 on 2020-06-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_ign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_prof_pic.jpg', upload_to='profile_pics'),
        ),
    ]
